In [1]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as la
import math

In [21]:
def m(d):
    return np.array(d)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [10]:
A1 = m([[3],[2],[5]])
W1 = m([[1.1,0.1],
        [1.3,2.0],
        [1.5,1.7]]).T

print(W1)

W2 = m([[2.0,1.3],
        [1.2,1.7]])

print(W2)

[[1.1 1.3 1.5]
 [0.1 2.  1.7]]
[[2.  1.3]
 [1.2 1.7]]


In [6]:
A2 = W1.dot(A1)
print(A2)

[[13.4]
 [12.8]]


In [8]:
A3 = W2.dot(A2)
print(A3)

[[43.44]
 [37.84]]


In [18]:
print(sigmoid(A2))
print(sigmoid(A3))

[[0.99999848]
 [0.99999724]]
[[1.]
 [1.]]


In [55]:
xy=m([[.1,4.1,2.7,3.9,7.1,1.3,9.7,0.7,3.4,6.0],
[0,1,0,0,1,0,1,0,1,0]])
X = m([[1.1,4.1,2.7,3.9,7.1,1.3,9.7,0.7,3.4,6.0]])
y = m([[0,1,0,0,1,0,1,0,1,0]])
print(y)
print(X)

[[0 1 0 0 1 0 1 0 1 0]]
[[1.1 4.1 2.7 3.9 7.1 1.3 9.7 0.7 3.4 6. ]]
